import { Center, Box, Button, Stack, Image } from "@mantine/core";
import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <Box sx={{ height: "100%" }}>
      <Head>
        <title>PokéSteph</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Center sx={{ height: "100%" }}>
        <Stack>
          <Image src="/media/PokeDex Logo.png" alt="PokéSteph" />
          <Link href="/pokemon" passHref>
            <Button component="a" sx={{ margin: "0 auto" }}>
              Show all pokemon
            </Button>
          </Link>
        </Stack>
      </Center>
    </Box>
  );
}
