export const TYPE_COLORS = {
  NORMAL: "grey",
  FIRE: "red",
  WATER: "blue",
  ELECTRIC: "yellow",
  GRASS: "green",
  ICE: "blue.2",
  FIGHTING: "red.4",
  POISON: "purple",
  GROUND: "brown",
  FLYING: "orange",
  PSYCHIC: "violet",
  BUG: "lime",
  ROCK: "grey.4",
  GHOST: "white",
  DRAGON: "red.3",
  DARK: "black",
  STEEL: "darkGray",
  FAIRY: "pink",
};
