export const TYPE_ICONS = {
  normal: "",
  fire: "/media/icons/elements/fire.png",
  water: "/media/icons/elements/water.png",
  electric: "/media/icons/elements/lightning.png",
  grass: "/media/icons/elements/green-tea.png",
  ice: "",
  fighting: "",
  poison: "/media/icons/elements/poison.png",
  ground: "",
  flying: "",
  psychic: "",
  bug: "",
  rock: "/media/icons/elements/rock.png",
  ghost: "",
  dragon: "",
  dark: "",
  steel: "",
  fairy: "",
};
